---
- name: Assert that prerequisites exist
  tags: ius
  assert:
    that:
      - ius_pkg is defined
      - ius_rel is defined

- name: Set ius facts (RedHat)
  tags: ius
  set_fact:
    ius_archive: 'Redhat'
    ius_dist: "rhel{{ ius_rel }}"
    ius_repo: "ius-el{{ ius_rel }}"
  when: ansible_distribution == 'RedHat'

- name: Set ius facts (CentOS)
  tags: ius
  set_fact:
    ius_archive: 'CentOS'
    ius_dist: "centos{{ ius_rel }}"
    ius_repo: "ius-centos{{ ius_rel }}"
  when: ansible_distribution == 'CentOS'

- name: Generate random package name
  tags: ius
  command: mktemp -u --suffix .rpm
  register: ius_mktemp

- name: Fetch {{ ius_pkg }} to temporary destination
  tags: ius
  get_url:
    url: "http://{{ ius_dist }}.iuscommunity.org/{{ ius_pkg }}.rpm"
    dest: "{{ ius_mktemp.stdout }}"
  register: ius_get_url
  when: ius_mktemp|success

- name: Ensure that the {{ ius_pkg }} package is installed
  tags: ius
  yum:
    name: "{{ item }}"
    state: present
  register: ius_yum
  with_items: "{{ ius_mktemp.stdout }}"
  when: ius_get_url|success

- name: Applying {{ ius_pkg }} configurations
  tags: ius
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: ius.repo.j2, dst: /etc/yum.repos.d/ius.repo }
    - { src: ius-archive.repo.j2, dst: /etc/yum.repos.d/ius-archive.repo }
    - { src: ius-dev.repo.j2, dst: /etc/yum.repos.d/ius-dev.repo }
    - { src: ius-testing.repo.j2, dst: /etc/yum.repos.d/ius-testing.repo }
  when: ius_yum|success

- name: Prune temporary package from the filesystem
  tags: ius
  file:
    path: "{{ ius_mktemp.stdout }}"
    state: absent
  when:
    - ius_mktemp|success
    - ius_yum|success
...
